# Generated by Django 3.0.6 on 2020-05-05 18:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('proposal', models.TextField()),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('legal_approved', models.BooleanField(default=False)),
                ('finance_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.CreateModel(
            name='ApplicationNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('application_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationProcess')),
            ],
        ),
    ]
